# Generated by Django 4.1.5 on 2023-03-04 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default='NGO1', max_length=40)),
                ('femail', models.CharField(max_length=40)),
                ('country', models.CharField(choices=[('India', 'India'), ('Canada', 'Canada'), ('Other', 'Other')], max_length=50)),
                ('desc', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('frname', models.CharField(default='NGO1', max_length=40)),
                ('frphone', models.TextField(max_length=13)),
                ('eventdesc', models.TextField()),
                ('funds', models.TextField()),
                ('documents', models.FileField(upload_to='files')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('orgname', models.CharField(default='NGO1', max_length=40)),
                ('phone', models.TextField(max_length=13)),
                ('previouswork', models.TextField()),
                ('futuregoals', models.TextField()),
                ('fundingneeds', models.TextField()),
                ('files', models.FileField(upload_to='files')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('Philanthropic', 'Philanthropic'), ('NGO', 'NGO')], max_length=50)),
                ('password', models.CharField(default='nit-hackathon@512', max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Philanthropist', 'Philanthropist'), ('NGO', 'NGO')], default='NGO', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
