# Generated by Django 4.1.6 on 2023-02-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('orgname', models.CharField(default='NGO1', max_length=40)),
                ('phone', models.TextField(max_length=13)),
                ('previouswork', models.TextField()),
                ('futuregoals', models.TextField()),
                ('fundingneeds', models.TextField()),
                ('files', models.FileField(upload_to='files')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('Philanthropic', 'Philanthropic'), ('NGO', 'NGO')], max_length=50)),
                ('password', models.CharField(default='nit-hackathon@512', max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
