# Generated by Django 4.1.6 on 2023-02-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodcauses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default='NGO1', max_length=40)),
                ('femail', models.CharField(max_length=40)),
                ('country', models.CharField(choices=[('India', 'India'), ('Canada', 'Canada'), ('Other', 'Other')], max_length=50)),
                ('desc', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
