# Generated by Django 4.1.6 on 2023-02-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodcauses', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('frname', models.CharField(default='NGO1', max_length=40)),
                ('frphone', models.TextField(max_length=13)),
                ('eventdesc', models.TextField()),
                ('funds', models.TextField()),
                ('documents', models.FileField(upload_to='files')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
